name: ODVPlugin
version: 1.0
main: de.pauhull.onedayvaro.OneDayVaro
author: pauhull
depend: [CoinsAPI]

load: POSTWORLD

commands:
  setlocation:
  config:
  start:
  addspawn:
  removespawn:
  globalmute:
  teams:
  stats:
  host:
  helphost:
  helpop: